const Errors = {
  SOME_THING_WRONG: "SOME_THING_WRONG",
  USER_IS_EXIST: "USER_IS_EXIST",
  USERNAME_IS_WRONG: "USERNAME_IS_WRONG",
  PASSWORD_IS_WRONG: "PASSWORD_IS_WRONG",
  AGE_NOT_EXIST: "AGE_NOT_EXIST",
  TYPE_REQUIRED: "TYPE_REQUIRED",
  TYPE_NOT_EXIST: "TYPE_NOT_EXIST",
  ROOM_NOT_EXIST: "ROOM_NOT_EXIST",
  ROOM_ID_REQUIRED: "ROOM_ID_REQUIRED",
  TYPE_NOT_EXIST: "TYPE_NOT_EXIST",
  IMAGE_TYPE_REQUIRED: "IMAGE_TYPE_REQUIRED",
  DISTRICT_NOT_EXIST: "DISTRICT_NOT_EXIST"
};

module.exports = Errors;
