const Errors = {
  SOME_THING_WRONG: "SOME_THING_WRONG",
  USER_IS_EXIST: "USER_IS_EXIST",
  USERNAME_IS_WRONG: "USERNAME_IS_WRONG",
  PASSWORD_IS_WRONG: "PASSWORD_IS_WRONG",
  AGE_NOT_EXIST: "AGE_NOT_EXIST",
  TYPE_REQUIRED: "TYPE_REQUIRED",
  TYPE_NOT_EXIST: "TYPE_NOT_EXIST",
  ROOM_NOT_EXIST: "ROOM_NOT_EXIST",
  ROOM_ID_REQUIRED: "ROOM_ID_REQUIRED",
  TYPE_NOT_EXIST: "TYPE_NOT_EXIST",
  IMAGE_TYPE_REQUIRED: "IMAGE_TYPE_REQUIRED",
  DISTRICT_NOT_EXIST: "DISTRICT_NOT_EXIST",
  ROOM_NOT_USERS: "ROOM_NOT_USERS",
  ROOM_NOT_READY: "ROOM_NOT_READY",
  ROOM_WAITING_RESPONSE: "ROOM_WAITING_RESPONSE",
  RETAILING_NOT_FOUND: "RETAILING_NOT_FOUND",
  WHAT_ARE_U_DOING: "WHAT_ARE_U_DOING",
  RETAILING_CAN_NOT_DEL: "RETAILING_CAN_NOT_DEL",
  RETAILING_STATUS_NOT_ALLOWED: "RETAILING_STATUS_NOT_ALLOWED"
};

module.exports = Errors;
