const Errors = {
  SOME_THING_WRONG: "SOME_THING_WRONG",
  USER_IS_EXIST: "USER_IS_EXIST",
  USERNAME_IS_WRONG: "USERNAME_IS_WRONG",
  PASSWORD_IS_WRONG: "PASSWORD_IS_WRONG",
  AGE_NOT_EXIST: "AGE_NOT_EXIST",
  COLOR_REQUIRED: "COLOR_REQUIRED",
  COLOR_NOT_EXIST: "COLOR_NOT_EXIST",
  GENDER_NOT_EXIST: "GENDER_NOT_EXIST",
  PRODUCT_NOT_EXIST: "PRODUCT_NOT_EXIST",
  PRODUCT_ID_REQUIRED: "PRODUCT_ID_REQUIRED",
  TYPE_NOT_EXIST: "TYPE_NOT_EXIST"
};

module.exports = Errors;
